name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - name: Checking your code format
        run: csbt scalafmtCheckAll headerCheck test:headerCheck
      - name: Run tests
        run: csbt test
